apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  jwt-secret-key: your-super-secret-jwt-key-change-in-production
  mongo-uri: mongodb://admin:supersecretpassword@mongodb:27017/muchtodo?authSource=admin
